version: '3.8'

services:

  book_review_app:
    container_name: book_review_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: book-review
      DB_SSLMODE: disable
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    container_name: book_review_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book-review
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network

volumes:
  postgres-data:

networks:
  network:
    driver: bridge
